### ISSUE TITLE
Incorrect temperature as noted in your Readme

### ISSUE THREAD

**Issue by csobsidian** [koenvervloesem/M5Stack-Air-Quality-ESPHome#3]
I believe you may be having an issue with temperature because uFire's library does not respect the polling rate of the SHT20. In _your_ SHT20 class's update method you are asking for temperature(), humidity(), vpd(), and dew_point(). If you look at uFire's code this will poll for the temperature 3 times. Even limiting yourself to once per second still exceeds the recommended polling rate. Does your temperature reading get better if you call your update at a slower rate?

**Comment by koenvervloesem** [comment]
Good point, thanks for looking into this! I've changed the polling rate to five seconds now to be sure, but this doesn't change the measured temperatures in my case.

**Comment by CarManBelarus** [comment]
First, According to my investigations, DHT sensor is situated far from other circuits and may hardly be affected by other parts.
Second. There is no time lag just after circuit start, in case of self warming up the difference will increase with time. 
And next, the difference is about 10 degrees, it's too much to be affected by sensor itself.

So i guess, the measurement error is caused by other reasons (maybe some soldering mistakes or some shifts in data bus)
In this case, i think you may safely add calibration to the sensor. something like this:

```
      - name: "Temperature"
        id: sensor_temperature
        unit_of_measurement: °C
        accuracy_decimals: 2
        filters:
          - calibrate_linear:
              - 33.6 -> 23.5
              - 12.0 -> 5.0
      - name: "Humidity"
        id: sensor_humidity
        unit_of_measurement: "%"
        accuracy_decimals: 2
        filters:
            - calibrate_linear:
                - 35.0 -> 52.6
                - 51.0 -> 70.0
```

I used these values just measuring values indoors and outdoors along with another sensor. Some more measurements must be done to determine calibration values more precise.
![IMG_20240212_151340](https://github.com/koenvervloesem/M5Stack-Air-Quality-ESPHome/assets/24219338/793cb64e-c695-4d87-91ef-a81618ec1048)
![IMG_20240212_151426](https://github.com/koenvervloesem/M5Stack-Air-Quality-ESPHome/assets/24219338/5b9f6592-94fd-4eb5-a792-de0b2442b5a4)
